# Generated by Django 5.1.1 on 2024-10-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='data_loader.genre'),
        ),
    ]
