# Generated by Django 5.1.1 on 2024-10-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0003_genre_created_at_genre_is_deleted_genre_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Gênero', 'verbose_name_plural': 'Gêneros'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
    ]
