# Generated by Django 5.1.1 on 2024-10-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_loader', '0004_alter_genre_options_alter_movie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
